### ISSUE TITLE
Unnecessary sleep

### ISSUE THREAD

**Issue by mas0nd** [praetorian-inc/gato#21]
https://github.com/praetorian-inc/gato/blob/b347c55a9142944b4d9cd362ed01daeebb3938ab/gato/github/search.py#L55

While we likely need some sleep in this code block for the frequency of requests, I'm not sure we need a one minute sleep to enumerate even the simplest of organizations.

**Comment by mas0nd** [comment]
@AdnaneKhan

**Comment by AdnaneKhan** [comment]
Yes, this current sleep exists to prevent calls to the code search API in rapid succession, often triggering the secondary rate limit when searching an organization with many repositories. 

The ideal fix for this will be to detect if the result set is complete and immediately exit instead of waiting and making a second request. While working on the fix for the search API error handling, I experimented with some checks; however, I saw some inconsistent behavior from the API related to the `total_count` and `incomplete_results` response fields. We can't just check if the result count is less than the pagination cap, as that will cause missed results since the API will sometimes return 30-40 results but have a total count in the hundreds.

**Comment by mas0nd** [comment]
I've made a couple of edits in `fix/appropriate-sleeps` that potentially address a couple of these issues. First, the search module now respects the ratelimiting headers, so sleeps are minimized. Second, it respects the Links pagination header, so this should always pull ALL of the results from the search without any guessing/relying on counts. Finally, I've noticed that the Code Search API is super inconsistent, so we should try and find a solution or include a warning to that fact, assuming there aren't any incorrect assumptions in my changes, of course.
